export enum PowerStateEnum {
  CHARGING = 'CHARGING',
  FAULT = 'FAULT',
  FINISHED = 'FINISHED',
  PLUGGED = 'PLUGGED',
  PREPARING = 'PREPARING',
  UNKNOWN = 'UNKNOWN',
  UNPLUGGED = 'UNPLUGGED',
  STOPPED = 'STOPPED',
}
